### PR TITLE
work on parsing schema fields

### PR DESCRIPTION
**Pull request by radai-rosenblatt**
can now parse primitive fields, and some work on references

---
This change is [Reviewable](https://reviewable.io/reviews/linkedin/avro-util/186)

### CODE REVIEW

**Review by navina — APPROVED** [review]
lgtm!

**Review by srramach — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/linkedin/avro-util/186)* status: all files reviewed, 13 unresolved discussions (waiting on @radai-rosenblatt)

___
*[parser/src/main/java/com/linkedin/avroutil1/model/AvroSchemaField.java, line 35 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiXy7u70NdPNgCbqS_g:-MiXy7u88Inpf1fo_95s:baud1ol) ([raw file](https://github.com/linkedin/avro-util/blob/edaf5f8bcf8fca92d7e33080df995192d575e650/parser/src/main/java/com/linkedin/avroutil1/model/AvroSchemaField.java#L35)):*
> ```
> "schema cannot be null"
> ```

`"schema for " + name + " cannot be null"`
___
*[parser/src/main/java/com/linkedin/avroutil1/model/AvroSchemaField.java, line 60 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiXyQk26QchqvirrVFN:-MiXyQk26QchqvirrVFO:b-u3hw0m) ([raw file](https://github.com/linkedin/avro-util/blob/edaf5f8bcf8fca92d7e33080df995192d575e650/parser/src/main/java/com/linkedin/avroutil1/model/AvroSchemaField.java#L60)):*
> ```
> "recordSchema cannot be null"
> ```

Add `getName()` to the error message here.
___
*[parser/src/main/java/com/linkedin/avroutil1/model/AvroSchemaField.java, line 63 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiXy_nd5m7AcG9JEs9t:-MiXy_nd5m7AcG9JEs9u:b-4pj6qp) ([raw file](https://github.com/linkedin/avro-util/blob/edaf5f8bcf8fca92d7e33080df995192d575e650/parser/src/main/java/com/linkedin/avroutil1/model/AvroSchemaField.java#L63)):*
> ```
> "position cannot be negative"
> ```

Add `getName()` and `position` to the error message here.
___
*[parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java, line 9 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiXzkQ3-zkn4Ww3rcgV:-MiXzkQ3-zkn4Ww3rcgW:b-h1n959) ([raw file](https://github.com/linkedin/avro-util/blob/edaf5f8bcf8fca92d7e33080df995192d575e650/parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java#L9)):*
> ```Java
> package com.linkedin.avroutil1.model;
> 
> import com.sun.nio.sctp.IllegalReceiveException;
> ```

Why this particular type? Doesn't `IllegalArgumentException` suffice?
___
*[parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java, line 34 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY-Elf7u_CZEGgA-2L:-MiY-Elf7u_CZEGgA-2M:b-ligoc0) ([raw file](https://github.com/linkedin/avro-util/blob/edaf5f8bcf8fca92d7e33080df995192d575e650/parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java#L34)):*
> ```
> "argument cannot be null"
> ```

`"schema definition cannot be null"`
___
*[parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java, line 43 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY-LM5-W-TAY9tNLWs:-MiY-LM5-W-TAY9tNLWt:b-vcd5yc) ([raw file](https://github.com/linkedin/avro-util/blob/edaf5f8bcf8fca92d7e33080df995192d575e650/parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java#L43)):*
> ```
> "argument cannot be null"
> ```

`"schema reference cannot be null"`
___
*[parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java, line 73 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY-Z0e4mxm1rbtnu6n:-MiY-Z0e4mxm1rbtnu6o:b-8elsak) ([raw file](https://github.com/linkedin/avro-util/blob/edaf5f8bcf8fca92d7e33080df995192d575e650/parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java#L73)):*
> ```
> "this reference has 
> ```

`"reference " + ref + " has ...`
___
*[parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java, line 78 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiXw3h71SmTZfAwuNHO:-MiXw3h71SmTZfAwuNHP:b-b9qmy6) ([raw file](https://github.com/linkedin/avro-util/blob/edaf5f8bcf8fca92d7e33080df995192d575e650/parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java#L78)):*
> ```
> its
> ```

`it's`
___
*[parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java, line 101 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY341_0qaJ4oRoNgx9:-MiY341_0qaJ4oRoNgxA:b-b9qmy6) ([raw file](https://github.com/linkedin/avro-util/blob/edaf5f8bcf8fca92d7e33080df995192d575e650/parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java#L101)):*
> ```
> its
> ```

`it's`
___
*[parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java, line 108 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY3P9f8tQiW0cQb7Hw:-MiY3P9f8tQiW0cQb7Hx:b-uwdzv) ([raw file](https://github.com/linkedin/avro-util/blob/edaf5f8bcf8fca92d7e33080df995192d575e650/parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java#L108)):*
> ```Java
>                 }
>                 throw new UnsupportedOperationException("TBD");
>             case OBJECT: //record/enum/fixed/error
> ```

The [spec](https://avro.apache.org/docs/1.10.2/spec.html#schema_primitive) says that primitive types are also named types, e.g., `{"type": "string"}`. So maybe add a TODO to deal with those here?
___
*[parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java, line 147 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY5Ic_9fMVR1AypUeN:-MiY5IcaB7yoVbqjEKC1:b46fjco) ([raw file](https://github.com/linkedin/avro-util/blob/edaf5f8bcf8fca92d7e33080df995192d575e650/parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java#L147)):*
> ```Java
>                         AvroRecordSchema recordSchema = new AvroRecordSchema(
>                                 nameStr.getValue(), // != null
>                                 namespace,
> ```

AvroNamedSchema.getFullName() calls `namespace.isEmpty()` (line 27) without checking to see if namespace can be null (which, as supplied here, can be). Fix it to avoid NPE. (And add a test case where doc is not specified.)
___
*[parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonLocationImpl.java, line 39 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY0XTf1oaT58lrv3AA:-MiY0XTf1oaT58lrv3AB:b-dme4mz) ([raw file](https://github.com/linkedin/avro-util/blob/edaf5f8bcf8fca92d7e33080df995192d575e650/parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonLocationImpl.java#L39)):*
> ```
> columnNumber+"
> ```

Spaces around the `+`.
___
*[parser/src/test/resources/schemas/TestInvalidDocRecord.avsc, line 12 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY46_e5g2nj8zFeSN1:-MiY46_e5g2nj8zFeSN2:b-p1ipx7) ([raw file](https://github.com/linkedin/avro-util/blob/edaf5f8bcf8fca92d7e33080df995192d575e650/parser/src/test/resources/schemas/TestInvalidDocRecord.avsc#L12)):*
> ```JSON
>     }
>   ]
> }
> ```

This and the other `*.avsc` files here have some garbage chars at the end. Remove?

**Review by srramach — CHANGES_REQUESTED** [review]
> Reviewed 4 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/linkedin/avro-util/186)* status: all files reviewed, 13 unresolved discussions (waiting on @radai-rosenblatt)

___
*[parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java, line 147 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY5Ic_9fMVR1AypUeN:-MiY8A8u8yxd5WC0IOao:b9vnok5) ([raw file](https://github.com/linkedin/avro-util/blob/edaf5f8bcf8fca92d7e33080df995192d575e650/parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java#L147)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

AvroNamedSchema.getFullName() calls `namespace.isEmpty()` (line 27) without checking to see if namespace can be null (which, as supplied here, can be). Fix it to avoid NPE. (And add a test case where doc is not specified.)
</blockquote></details>

Small typo: I meant, "add a test case where _namespace_ is not specified."

**Review by radai-rosenblatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/linkedin/avro-util/186)* status: all files reviewed, 13 unresolved discussions (waiting on @radai-rosenblatt and @srramach)

___
*[parser/src/main/java/com/linkedin/avroutil1/model/AvroSchemaField.java, line 35 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiXy7u70NdPNgCbqS_g:-Mjl0wEWE_a7jmrliDeS:b-896fix) ([raw file](https://github.com/linkedin/avro-util/blob/45d276f0e46ae8ed9190a42c536a0ae1ece261a2/parser/src/main/java/com/linkedin/avroutil1/model/AvroSchemaField.java#L35)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

> ```
> "schema cannot be null"
> ```

`"schema for " + name + " cannot be null"`
</blockquote></details>

Done.
___
*[parser/src/main/java/com/linkedin/avroutil1/model/AvroSchemaField.java, line 60 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiXyQk26QchqvirrVFN:-Mjl1LyP9lHJUj5bNVyq:b-896fix) ([raw file](https://github.com/linkedin/avro-util/blob/45d276f0e46ae8ed9190a42c536a0ae1ece261a2/parser/src/main/java/com/linkedin/avroutil1/model/AvroSchemaField.java#L60)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

> ```
> "recordSchema cannot be null"
> ```

Add `getName()` to the error message here.
</blockquote></details>

Done.
___
*[parser/src/main/java/com/linkedin/avroutil1/model/AvroSchemaField.java, line 63 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiXy_nd5m7AcG9JEs9t:-Mjl1Miz20msXB0cg0Tp:b-896fix) ([raw file](https://github.com/linkedin/avro-util/blob/45d276f0e46ae8ed9190a42c536a0ae1ece261a2/parser/src/main/java/com/linkedin/avroutil1/model/AvroSchemaField.java#L63)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

> ```
> "position cannot be negative"
> ```

Add `getName()` and `position` to the error message here.
</blockquote></details>

Done.
___
*[parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java, line 9 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiXzkQ3-zkn4Ww3rcgV:-Mjl1eGL1HpmjL-ZNfjv:bfl924q) ([raw file](https://github.com/linkedin/avro-util/blob/45d276f0e46ae8ed9190a42c536a0ae1ece261a2/parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java#L9)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

Why this particular type? Doesn't `IllegalArgumentException` suffice?
</blockquote></details>

auto complete error on my end. oops
___
*[parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java, line 34 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY-Elf7u_CZEGgA-2L:-MjlODJy3jhUnNVhPj0u:b-896fix) ([raw file](https://github.com/linkedin/avro-util/blob/45d276f0e46ae8ed9190a42c536a0ae1ece261a2/parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java#L34)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

> ```
> "argument cannot be null"
> ```

`"schema definition cannot be null"`
</blockquote></details>

Done.
___
*[parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java, line 43 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY-LM5-W-TAY9tNLWs:-MjlOFs11YU0-WQYJAt7:b-896fix) ([raw file](https://github.com/linkedin/avro-util/blob/45d276f0e46ae8ed9190a42c536a0ae1ece261a2/parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java#L43)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

> ```
> "argument cannot be null"
> ```

`"schema reference cannot be null"`
</blockquote></details>

Done.
___
*[parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java, line 73 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY-Z0e4mxm1rbtnu6n:-MjlONsJDtMemzp0OZHn:b-896fix) ([raw file](https://github.com/linkedin/avro-util/blob/45d276f0e46ae8ed9190a42c536a0ae1ece261a2/parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java#L73)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

> ```
> "this reference has 
> ```

`"reference " + ref + " has ...`
</blockquote></details>

Done.
___
*[parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java, line 78 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiXw3h71SmTZfAwuNHO:-MjlORmf2POIkl0dEXvc:b-896fix) ([raw file](https://github.com/linkedin/avro-util/blob/45d276f0e46ae8ed9190a42c536a0ae1ece261a2/parser/src/main/java/com/linkedin/avroutil1/model/SchemaOrRef.java#L78)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

> ```
> its
> ```

`it's`
</blockquote></details>

Done.
___
*[parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java, line 101 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY341_0qaJ4oRoNgx9:-MjlOXw7AgryheeYtxaG:b-896fix) ([raw file](https://github.com/linkedin/avro-util/blob/45d276f0e46ae8ed9190a42c536a0ae1ece261a2/parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java#L101)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

> ```
> its
> ```

`it's`
</blockquote></details>

Done.
___
*[parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java, line 147 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY5Ic_9fMVR1AypUeN:-MjlPQm4Arhpr8kyLnjb:b-44jy18) ([raw file](https://github.com/linkedin/avro-util/blob/45d276f0e46ae8ed9190a42c536a0ae1ece261a2/parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java#L147)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

Small typo: I meant, "add a test case where _namespace_ is not specified."
</blockquote></details>

added input validation

**Review by radai-rosenblatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/linkedin/avro-util/186)* status: all files reviewed, 13 unresolved discussions (waiting on @radai-rosenblatt and @srramach)

___
*[parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonLocationImpl.java, line 39 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY0XTf1oaT58lrv3AA:-MjlPprC33Md6Q0zTaUU:b-896fix) ([raw file](https://github.com/linkedin/avro-util/blob/45d276f0e46ae8ed9190a42c536a0ae1ece261a2/parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonLocationImpl.java#L39)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

> ```
> columnNumber+"
> ```

Spaces around the `+`.
</blockquote></details>

Done.
___
*[parser/src/test/resources/schemas/TestInvalidDocRecord.avsc, line 12 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY46_e5g2nj8zFeSN1:-MjlPhMo1l9LD8lyY9q-:braf1n7) ([raw file](https://github.com/linkedin/avro-util/blob/45d276f0e46ae8ed9190a42c536a0ae1ece261a2/parser/src/test/resources/schemas/TestInvalidDocRecord.avsc#L12)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

This and the other `*.avsc` files here have some garbage chars at the end. Remove?
</blockquote></details>

i dont see any?

**Review by srramach — COMMENTED** [review]
:lgtm:

> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/linkedin/avro-util/186#-:-Mk0Qn5_6_rpzSeMvE0y:bnfp4nl)* status: all files reviewed, 2 unresolved discussions

___
*[parser/src/test/resources/schemas/TestInvalidDocRecord.avsc, line 12 at r1](https://reviewable.io/reviews/linkedin/avro-util/186#-MiY46_e5g2nj8zFeSN1:-Mk0Pv9NBPRSGVw6lnDi:bv3sjqd) ([raw file](https://github.com/linkedin/avro-util/blob/45d276f0e46ae8ed9190a42c536a0ae1ece261a2/parser/src/test/resources/schemas/TestInvalidDocRecord.avsc#L12)):*
<details><summary><i>Previously, radai-rosenblatt (Radai Rosenblatt) wrote…</i></summary><blockquote>

i dont see any?
</blockquote></details>

I think perhaps they don't end in a newline? I see two red outlined rectangles in the reviewable.io UI; am guessing that indicates "no newline at the end of a text file", based on this [bug report](https://github.com/Reviewable/Reviewable/issues/295) from long ago.

**Pull request merged**
