### PR TITLE
add Helper.parse(InputStream)

### PR DESCRIPTION
**Pull request by radai-rosenblatt**
addresses #185

---
This change is [Reviewable](https://reviewable.io/reviews/linkedin/avro-util/187)

### CODE REVIEW

**Review by srramach — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/linkedin/avro-util/187)* status: all files reviewed, 2 unresolved discussions (waiting on @radai-rosenblatt)

___
*[helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java, line 356 at r1](https://reviewable.io/reviews/linkedin/avro-util/187#-MiO1E80BqCgmRPy9zGG:-MiO1E80BqCgmRPy9zGH:b-qz6f5l) ([raw file](https://github.com/linkedin/avro-util/blob/4c9bd0383e1d5061611a82508fd4fb30996607e5/helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java#L356)):*
> ```Java
> 
>   /**
>    * parses a single avro schema json String (see <a href="http://google.com">spec</a>), which may refer to others.
> ```

Update this comment. It should refer to a stream (instead of a `String`). The link should go to the Avro spec instead of a placeholder.
___
*[helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java, line 370 at r1](https://reviewable.io/reviews/linkedin/avro-util/187#-MiO2VGzAEa7vyDzLFlJ:-MiO2VGzAEa7vyDzLFlK:b-8psrcp) ([raw file](https://github.com/linkedin/avro-util/blob/4c9bd0383e1d5061611a82508fd4fb30996607e5/helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java#L370)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     try (InputStreamReader reader = new InputStreamReader(schemaJson, StandardCharsets.UTF_8)) {
>       char[] buffer = new char[8192];
>       int charsRead = reader.read(buffer);
>       while (charsRead > -1) {
>         sb.append(buffer, 0, charsRead);
>         charsRead = reader.read(buffer);
>       }
>     }
> ```
</details>


This whole thing could be replaced with [IOUtils.toString()](https://commons.apache.org/proper/commons-io/javadocs/api-release/org/apache/commons/io/IOUtils.html#toString-java.io.InputStream-java.nio.charset.Charset-)

**Review by radai-rosenblatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/linkedin/avro-util/187)* status: all files reviewed, 2 unresolved discussions (waiting on @radai-rosenblatt and @srramach)

___
*[helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java, line 370 at r1](https://reviewable.io/reviews/linkedin/avro-util/187#-MiO2VGzAEa7vyDzLFlJ:-MiOmA474NT-Bb1wlrOP:bo0g19x) ([raw file](https://github.com/linkedin/avro-util/blob/4c9bd0383e1d5061611a82508fd4fb30996607e5/helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java#L370)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

> ```
>     try (InputStreamReader reader = new InputStreamReader(schemaJson, StandardCharsets.UTF_8)) {
>       char[] buffer = new char[8192];
>       int charsRead = reader.read(buffer);
>       while (charsRead > -1) {
>         sb.append(buffer, 0, charsRead);
>         charsRead = reader.read(buffer);
>       }
>     }
> ```

This whole thing could be replaced with [IOUtils.toString()](https://commons.apache.org/proper/commons-io/javadocs/api-release/org/apache/commons/io/IOUtils.html#toString-java.io.InputStream-java.nio.charset.Charset-)
</blockquote></details>

it cuold, but i dont think its worth adding a dependency on commons-io for this simple loop?

**Review by radai-rosenblatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/linkedin/avro-util/187)* status: all files reviewed, 2 unresolved discussions (waiting on @srramach)

___
*[helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java, line 356 at r1](https://reviewable.io/reviews/linkedin/avro-util/187#-MiO1E80BqCgmRPy9zGG:-MiOmXUF0E9d7HQTTHQr:b-896fix) ([raw file](https://github.com/linkedin/avro-util/blob/4c9bd0383e1d5061611a82508fd4fb30996607e5/helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java#L356)):*
<details><summary><i>Previously, srramach (Sreeram Ramachandran) wrote…</i></summary><blockquote>

Update this comment. It should refer to a stream (instead of a `String`). The link should go to the Avro spec instead of a placeholder.
</blockquote></details>

Done.

**Review by srramach — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/linkedin/avro-util/187#-:-MiPLFq2DIX-rP7pgec4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @radai-rosenblatt)

___
*[helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java, line 370 at r1](https://reviewable.io/reviews/linkedin/avro-util/187#-MiO2VGzAEa7vyDzLFlJ:-MiPKwEg3AERWxjW6HLs:b-gxztsp) ([raw file](https://github.com/linkedin/avro-util/blob/4c9bd0383e1d5061611a82508fd4fb30996607e5/helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java#L370)):*
<details><summary><i>Previously, radai-rosenblatt (Radai Rosenblatt) wrote…</i></summary><blockquote>

it cuold, but i dont think its worth adding a dependency on commons-io for this simple loop?
</blockquote></details>

Fair enough.

**Pull request merged**
